name: Various
version: '${version}'
main: com.charlotte04.various.VariousPlugin
api-version: 1.18
authors: [ charlotte ]
commands:
  various:
    aliases: [ vs ]
    usage: "/<command> <>"
  effect_item:
    aliases: [ ei ]
    usage: "/<command> <itemName>"
  trade:
    aliases: [ tr ]
    usage: "/<command> <>"